<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\ImgLogo;

class FillImgLogo extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
              'club_code'=>'0100',
              'url'=>'assets/img/img_logo/0100.png'
            ],
            [
                'club_code'=>'0102',
                'url'=>'assets/img/img_logo/0102.jpg'
            ],
            [
                'club_code'=>'0106',
                'url'=>'assets/img/img_logo/0106.jpg'
            ],
            [
                'club_code'=>'0108',
                'url'=>'assets/img/img_logo/0108.jpg'
            ],
            [
                'club_code'=>'0110',
                'url'=>'assets/img/img_logo/0110.jpg'
            ],
            [
                'club_code'=>'0111',
                'url'=>'assets/img/img_logo/0111.jpg'
            ],
            [
                'club_code'=>'0117',
                'url'=>'assets/img/img_logo/0117.jpg'
            ],
            [
                'club_code'=>'0119',
                'url'=>'assets/img/img_logo/0119.png'
            ],
            [
                'club_code'=>'0200',
                'url'=>'assets/img/img_logo/0200.png'
            ],
            [
                'club_code'=>'0201',
                'url'=>'assets/img/img_logo/0201.png'
            ],
            [
                'club_code'=>'0202',
                'url'=>'assets/img/img_logo/0202.png'
            ],
            [
                'club_code'=>'0208',
                'url'=>'assets/img/img_logo/0208.jpg'
            ],
            [
                'club_code'=>'0213',
                'url'=>'assets/img/img_logo/0213.jpg'
            ],
            [
                'club_code'=>'0220',
                'url'=>'assets/img/img_logo/0220.jpg'
            ],
            [
                'club_code'=>'0224',
                'url'=>'assets/img/img_logo/0224.jpg'
            ],
            [
                'club_code'=>'0234',
                'url'=>'assets/img/img_logo/0234.jpg'
            ],
            [
                'club_code'=>'0236',
                'url'=>'assets/img/img_logo/0236.jpg'
            ],
            [
                'club_code'=>'0238',
                'url'=>'assets/img/img_logo/0238.JPG'
            ],
            [
                'club_code'=>'1100',
                'url'=>'assets/img/img_logo/1100.jpg'
            ],
            [
                'club_code'=>'1101',
                'url'=>'assets/img/img_logo/1101.jpg'
            ],
            [
                'club_code'=>'1106',
                'url'=>'assets/img/img_logo/1106.png'
            ],
            [
                'club_code'=>'1107',
                'url'=>'assets/img/img_logo/1107.jpg'
            ],
            [
                'club_code'=>'1109',
                'url'=>'assets/img/img_logo/1109.jpg'
            ],
            [
                'club_code'=>'1110',
                'url'=>'assets/img/img_logo/1110.png'
            ],
            [
                'club_code'=>'1116',
                'url'=>'assets/img/img_logo/1116.jpg'
            ],
            [
                'club_code'=>'1119',
                'url'=>'assets/img/img_logo/1119.jpg'
            ],
            [
                'club_code'=>'1128',
                'url'=>'assets/img/img_logo/1128.png'
            ],
            [
                'club_code'=>'4400',
                'url'=>'assets/img/img_logo/4400.jpg'
            ],
            [
                'club_code'=>'4402',
                'url'=>'assets/img/img_logo/4402.jpg'
            ],
            [
                'club_code'=>'4405',
                'url'=>'assets/img/img_logo/4405.png'
            ],
            [
                'club_code'=>'4409',
                'url'=>'assets/img/img_logo/4409.jpg'
            ],
            [
                'club_code'=>'7700',
                'url'=>'assets/img/img_logo/7700.jpg'
            ],
            [
                'club_code'=>'7705',
                'url'=>'assets/img/img_logo/7705.jpg'
            ],
            [
                'club_code'=>'7706',
                'url'=>'assets/img/img_logo/7706.png'
            ],
            [
                'club_code'=>'7712',
                'url'=>'assets/img/img_logo/7712.jpg'
            ],
            [
                'club_code'=>'7713',
                'url'=>'assets/img/img_logo/7713.png'
            ],
            [
                'club_code'=>'7721',
                'url'=>'assets/img/img_logo/7721.jpg'
            ],
            [
                'club_code'=>'7739',
                'url'=>'assets/img/img_logo/7739.png'
            ],
            [
                'club_code'=>'7740',
                'url'=>'assets/img/img_logo/7740.jpg'
            ],
            [
                'club_code'=>'7743',
                'url'=>'assets/img/img_logo/7743.jpg'
            ],
            [
                'club_code'=>'7744',
                'url'=>'assets/img/img_logo/7744.png'
            ],
            [
                'club_code'=>'7747',
                'url'=>'assets/img/img_logo/7747.png'
            ],
            [
                'club_code'=>'7752',
                'url'=>'assets/img/img_logo/7752.jpg'
            ],
            [
                'club_code'=>'7753',
                'url'=>'assets/img/img_logo/7753.png'
            ],
            [
                'club_code'=>'7756',
                'url'=>'assets/img/img_logo/7756.jpg'
            ],
            [
                'club_code'=>'7758',
                'url'=>'assets/img/img_logo/7758.png'
            ],
            [
                'club_code'=>'7769',
                'url'=>'assets/img/img_logo/7769.jpg'
            ],
            [
                'club_code'=>'7770',
                'url'=>'assets/img/img_logo/7770.jpg'
            ],
            [
                'club_code'=>'7772',
                'url'=>'assets/img/img_logo/7772.jpg'
            ],
            [
                'club_code'=>'7773',
                'url'=>'assets/img/img_logo/7773.jpg'
            ],
            [
                'club_code'=>'7776',
                'url'=>'assets/img/img_logo/7776.png'
            ],
            [
                'club_code'=>'8800',
                'url'=>'assets/img/img_logo/8800.jpg'
            ],
            [
                'club_code'=>'8803',
                'url'=>'assets/img/img_logo/8803.jpg'
            ],
            [
                'club_code'=>'8804',
                'url'=>'assets/img/img_logo/8804.png'
            ],
            [
                'club_code'=>'8808',
                'url'=>'assets/img/img_logo/8808.jpg'
            ],
            [
                'club_code'=>'8816',
                'url'=>'assets/img/img_logo/8816.JPG'
            ],
            [
                'club_code'=>'8816',
                'url'=>'assets/img/img_logo/8816.png'
            ],
            [
                'club_code'=>'8818',
                'url'=>'assets/img/img_logo/8818.jpg'
            ],
            [
                'club_code'=>'8820',
                'url'=>'assets/img/img_logo/8820.jpg'
            ],
            [
                'club_code'=>'8828',
                'url'=>'assets/img/img_logo/8828.png'
            ],
            [
                'club_code'=>'8833',
                'url'=>'assets/img/img_logo/8833.jpg'
            ],
            [
                'club_code'=>'8834',
                'url'=>'assets/img/img_logo/8834.jpg'
            ],
            [
                'club_code'=>'8842',
                'url'=>'assets/img/img_logo/8842.jpg'
            ],
            [
                'club_code'=>'8843',
                'url'=>'assets/img/img_logo/8843.jpg'
            ],
            [
                'club_code'=>'9900',
                'url'=>'assets/img/img_logo/9900.png'
            ],
            [
                'club_code'=>'9901',
                'url'=>'assets/img/img_logo/9901.jpg'
            ],
            [
                'club_code'=>'9906',
                'url'=>'assets/img/img_logo/9906.jpg'
            ],
            [
                'club_code'=>'9912',
                'url'=>'assets/img/img_logo/9912.png'
            ],
            [
                'club_code'=>'9919',
                'url'=>'assets/img/img_logo/9919.jpg'
            ],
            [
                'club_code'=>'AM00',
                'url'=>'assets/img/img_logo/AM00.jpg'
            ],
            [
                'club_code'=>'AM04',
                'url'=>'assets/img/img_logo/AM04.jpg'
            ],
            [
                'club_code'=>'AM05',
                'url'=>'assets/img/img_logo/AM05.jpeg'
            ],
            [
                'club_code'=>'AM06',
                'url'=>'assets/img/img_logo/AM06.jpg'
            ],
            [
                'club_code'=>'AM07',
                'url'=>'assets/img/img_logo/AM07.jpg'
            ],
            [
                'club_code'=>'AM10',
                'url'=>'assets/img/img_logo/AM10.jpeg'
            ],
            [
                'club_code'=>'AM10',
                'url'=>'assets/img/img_logo/AM10.png'
            ],
            [
                'club_code'=>'AM11',
                'url'=>'assets/img/img_logo/AM11.jpg'
            ],
            [
                'club_code'=>'AM15',
                'url'=>'assets/img/img_logo/AM15.png'
            ],
            [
                'club_code'=>'AM23',
                'url'=>'assets/img/img_logo/AM23.png'
            ],
            [
                'club_code'=>'AM24',
                'url'=>'assets/img/img_logo/AM24.JPG'
            ],
            [
                'club_code'=>'AM29',
                'url'=>'assets/img/img_logo/AM29.jpg'
            ],
            [
                'club_code'=>'AM42',
                'url'=>'assets/img/img_logo/AM42.jpg'
            ],
            [
                'club_code'=>'AM45',
                'url'=>'assets/img/img_logo/AM45.jpg'
            ],
            [
                'club_code'=>'AM58',
                'url'=>'assets/img/img_logo/AM58.jpg'
            ],
            [
                'club_code'=>'AM59',
                'url'=>'assets/img/img_logo/AM59.jpg'
            ],
            [
                'club_code'=>'AM65',
                'url'=>'assets/img/img_logo/AM65.jpg'
            ],
            [
                'club_code'=>'AM67',
                'url'=>'assets/img/img_logo/AM67.jpg'
            ],
            [
                'club_code'=>'AM72',
                'url'=>'assets/img/img_logo/AM72.jpg'
            ],
            [
                'club_code'=>'AM75',
                'url'=>'assets/img/img_logo/AM75.jpg'
            ],
            [
                'club_code'=>'AM83',
                'url'=>'assets/img/img_logo/AM83.png'
            ],
            [
                'club_code'=>'AM85',
                'url'=>'assets/img/img_logo/AM85.jpg'
            ],
            [
                'club_code'=>'AM91',
                'url'=>'assets/img/img_logo/AM91.jpg'
            ],
            [
                'club_code'=>'AM96',
                'url'=>'assets/img/img_logo/AM96.png'
            ],
            [
                'club_code'=>'AMB2',
                'url'=>'assets/img/img_logo/AMB2.jpg'
            ],
            [
                'club_code'=>'AMB6',
                'url'=>'assets/img/img_logo/AMB6.jpg'
            ],
            [
                'club_code'=>'AMB6',
                'url'=>'assets/img/img_logo/AMB6.png'
            ],
            [
                'club_code'=>'AMC3',
                'url'=>'assets/img/img_logo/AMC3.jpeg'
            ],
            [
                'club_code'=>'AMC3',
                'url'=>'assets/img/img_logo/AMC3.jpg'
            ],
            [
                'club_code'=>'AMC7',
                'url'=>'assets/img/img_logo/AMC7.jpg'
            ],
            [
                'club_code'=>'AMC8',
                'url'=>'assets/img/img_logo/AMC8.jpg'
            ],
            [
                'club_code'=>'AMD2',
                'url'=>'assets/img/img_logo/AMD2.jpg'
            ],
            [
                'club_code'=>'AMD5',
                'url'=>'assets/img/img_logo/AMD5.jpg'
            ],
            [
                'club_code'=>'AME4',
                'url'=>'assets/img/img_logo/AME4.jpg'
            ],
            [
                'club_code'=>'AME8',
                'url'=>'assets/img/img_logo/AME8.jpg'
            ],
            [
                'club_code'=>'AMF7',
                'url'=>'assets/img/img_logo/AMF7.jpg'
            ],
            [
                'club_code'=>'AMF8',
                'url'=>'assets/img/img_logo/AMF8.png'
            ],
            [
                'club_code'=>'AMG3',
                'url'=>'assets/img/img_logo/AMG3.jpg'
            ],
            [
                'club_code'=>'AMG8',
                'url'=>'assets/img/img_logo/AMG8.jpg'
            ],
            [
                'club_code'=>'AMI5',
                'url'=>'assets/img/img_logo/AMI5.jpg'
            ],
            [
                'club_code'=>'BP00',
                'url'=>'assets/img/img_logo/BP00.png'
            ],
            [
                'club_code'=>'BP02',
                'url'=>'assets/img/img_logo/BP02.jpg'
            ],
            [
                'club_code'=>'BP05',
                'url'=>'assets/img/img_logo/BP05.jpg'
            ],
            [
                'club_code'=>'BP06',
                'url'=>'assets/img/img_logo/BP06.png'
            ],
            [
                'club_code'=>'BP09',
                'url'=>'assets/img/img_logo/BP09.jpg'
            ],
            [
                'club_code'=>'BP12',
                'url'=>'assets/img/img_logo/BP12.png'
            ],
            [
                'club_code'=>'BP13',
                'url'=>'assets/img/img_logo/BP13.jpg'
            ],
            [
                'club_code'=>'BP14',
                'url'=>'assets/img/img_logo/BP14.png'
            ],
            [
                'club_code'=>'BP16',
                'url'=>'assets/img/img_logo/BP16.jpg'
            ],
            [
                'club_code'=>'BP19',
                'url'=>'assets/img/img_logo/BP19.png'
            ],
            [
                'club_code'=>'BP52',
                'url'=>'assets/img/img_logo/BP52.gif'
            ],
            [
                'club_code'=>'BP52',
                'url'=>'assets/img/img_logo/BP52.jpg'
            ],
            [
                'club_code'=>'BP55',
                'url'=>'assets/img/img_logo/BP55.jpg'
            ],
            [
                'club_code'=>'BP55_v',
                'url'=>'assets/img/img_logo/BP55_v.jpg'
            ],
            [
                'club_code'=>'BP58',
                'url'=>'assets/img/img_logo/BP58.png'
            ],
            [
                'club_code'=>'CB00',
                'url'=>'assets/img/img_logo/CB00.png'
            ],
            [
                'club_code'=>'CB01',
                'url'=>'assets/img/img_logo/CB01.png'
            ],
            [
                'club_code'=>'CB02',
                'url'=>'assets/img/img_logo/CB02.jpg'
            ],
            [
                'club_code'=>'CB03',
                'url'=>'assets/img/img_logo/CB03.jpg'
            ],
            [
                'club_code'=>'CB04',
                'url'=>'assets/img/img_logo/CB04.jpeg'
            ],
            [
                'club_code'=>'CB05',
                'url'=>'assets/img/img_logo/CB05.jpg'
            ],
            [
                'club_code'=>'CB07',
                'url'=>'assets/img/img_logo/CB07.jpeg'
            ],
            [
                'club_code'=>'CB08',
                'url'=>'assets/img/img_logo/CB08.jpg'
            ],
            [
                'club_code'=>'CB09',
                'url'=>'assets/img/img_logo/CB09.jpg'
            ],
            [
                'club_code'=>'CB18',
                'url'=>'assets/img/img_logo/CB18.png'
            ],
            [
                'club_code'=>'CB23',
                'url'=>'assets/img/img_logo/CB23.jpg'
            ],
            [
                'club_code'=>'CB26',
                'url'=>'assets/img/img_logo/CB26.jpg'
            ],
            [
                'club_code'=>'CB27',
                'url'=>'assets/img/img_logo/CB27.jpg'
            ],
            [
                'club_code'=>'CB28',
                'url'=>'assets/img/img_logo/CB28.png'
            ],
            [
                'club_code'=>'CB33',
                'url'=>'assets/img/img_logo/CB33.jpg'
            ],
            [
                'club_code'=>'CB34',
                'url'=>'assets/img/img_logo/CB34.png'
            ],
            [
                'club_code'=>'CB35',
                'url'=>'assets/img/img_logo/CB35.jpg'
            ],
            [
                'club_code'=>'CB36',
                'url'=>'assets/img/img_logo/CB36.jpg'
            ],
            [
                'club_code'=>'CB44',
                'url'=>'assets/img/img_logo/CB44.jpg'
            ],
            [
                'club_code'=>'CB54',
                'url'=>'assets/img/img_logo/CB54.jpg'
            ],
            [
                'club_code'=>'CB64',
                'url'=>'assets/img/img_logo/CB64.jpg'
            ],
            [
                'club_code'=>'CB65',
                'url'=>'assets/img/img_logo/CB65.jpeg'
            ],
            [
                'club_code'=>'CB69',
                'url'=>'assets/img/img_logo/CB69.jpg'
            ],
            [
                'club_code'=>'CB76',
                'url'=>'assets/img/img_logo/CB76.png'
            ],
            [
                'club_code'=>'CB96',
                'url'=>'assets/img/img_logo/CB96.jpg'
            ],
            [
                'club_code'=>'CB98',
                'url'=>'assets/img/img_logo/CB98.jpg'
            ],
            [
                'club_code'=>'CBB1',
                'url'=>'assets/img/img_logo/CBB1.jpeg'
            ],
            [
                'club_code'=>'CBB1.jpg',
                'url'=>'assets/img/img_logo/CBB1.jpg'
            ],
            [
                'club_code'=>'CE00',
                'url'=>'assets/img/img_logo/CE00.png'
            ],
            [
                'club_code'=>'CM00',
                'url'=>'assets/img/img_logo/CM00.png'
            ],
            [
                'club_code'=>'CM01',
                'url'=>'assets/img/img_logo/CM01.jpg'
            ],
            [
                'club_code'=>'CM01A',
                'url'=>'assets/img/img_logo/CM01A.jpg'
            ],
            [
                'club_code'=>'CM02',
                'url'=>'assets/img/img_logo/CM02.jpg'
            ],
            [
                'club_code'=>'CM05',
                'url'=>'assets/img/img_logo/CM05.png'
            ],
            [
                'club_code'=>'CM06',
                'url'=>'assets/img/img_logo/CM06.jpg'
            ],
            [
                'club_code'=>'CM08',
                'url'=>'assets/img/img_logo/CM08.png'
            ],
            [
                'club_code'=>'CM09',
                'url'=>'assets/img/img_logo/CM09.jpg'
            ],
            [
                'club_code'=>'CM11',
                'url'=>'assets/img/img_logo/CM11.jpg'
            ],
            [
                'club_code'=>'CM15',
                'url'=>'assets/img/img_logo/CM15.jpg'
            ],
            [
                'club_code'=>'CM18',
                'url'=>'assets/img/img_logo/CM18.jpg'
            ],
            [
                'club_code'=>'CM22',
                'url'=>'assets/img/img_logo/CM22.png'
            ],
            [
                'club_code'=>'CM33',
                'url'=>'assets/img/img_logo/CM33.jpg'
            ],
            [
                'club_code'=>'CM41',
                'url'=>'assets/img/img_logo/CM41.jpg'
            ],
            [
                'club_code'=>'CM60',
                'url'=>'assets/img/img_logo/CM60.png'
            ],
            [
                'club_code'=>'CM61',
                'url'=>'assets/img/img_logo/CM61.jpg'
            ],
            [
                'club_code'=>'CM66',
                'url'=>'assets/img/img_logo/CM66.png'
            ],
            [
                'club_code'=>'CMA8',
                'url'=>'assets/img/img_logo/CMA8.jpg'
            ],
            [
                'club_code'=>'CMA8A',
                'url'=>'assets/img/img_logo/CMA8A.jpg'
            ],
            [
                'club_code'=>'CMC8',
                'url'=>'assets/img/img_logo/CMC8.png'
            ],
            [
                'club_code'=>'CMD4',
                'url'=>'assets/img/img_logo/CMD4.jpg'
            ],
            [
                'club_code'=>'CMD7',
                'url'=>'assets/img/img_logo/CMD7.jpg'
            ],
            [
                'club_code'=>'CME5',
                'url'=>'assets/img/img_logo/CME5.jpeg'
            ],
            [
                'club_code'=>'CP00',
                'url'=>'assets/img/img_logo/CP00.jpg'
            ],
            [
                'club_code'=>'cp00.png',
                'url'=>'assets/img/img_logo/cp00.png'
            ],
            [
                'club_code'=>'CP01',
                'url'=>'assets/img/img_logo/CP01.jpg'
            ],
            [
                'club_code'=>'CP02',
                'url'=>'assets/img/img_logo/CP02.jpg'
            ],
            [
                'club_code'=>'CP03',
                'url'=>'assets/img/img_logo/CP03.jpg'
            ],
            [
                'club_code'=>'CP04',
                'url'=>'assets/img/img_logo/CP04.jpg'
            ],
            [
                'club_code'=>'CP05',
                'url'=>'assets/img/img_logo/CP05.jpg'
            ],
            [
                'club_code'=>'CP06',
                'url'=>'assets/img/img_logo/CP06.jpg'
            ],
            [
                'club_code'=>'CP09',
                'url'=>'assets/img/img_logo/CP09.jpg'
            ],
            [
                'club_code'=>'CP14',
                'url'=>'assets/img/img_logo/CP14.png'
            ],
            [
                'club_code'=>'CP15',
                'url'=>'assets/img/img_logo/CP15.png'
            ],
            [
                'club_code'=>'CP16',
                'url'=>'assets/img/img_logo/CP16.jpeg'
            ],
            [
                'club_code'=>'CP16',
                'url'=>'assets/img/img_logo/CP16.png'
            ],
            [
                'club_code'=>'CP17',
                'url'=>'assets/img/img_logo/CP17.jpg'
            ],
            [
                'club_code'=>'CP18',
                'url'=>'assets/img/img_logo/CP18.jpg'
            ],
            [
                'club_code'=>'CP20',
                'url'=>'assets/img/img_logo/CP20.jpg'
            ],
            [
                'club_code'=>'CP22',
                'url'=>'assets/img/img_logo/CP22.jpg'
            ],
            [
                'club_code'=>'CP26',
                'url'=>'assets/img/img_logo/CP26.jpg'
            ],
            [
                'club_code'=>'cp26',
                'url'=>'assets/img/img_logo/cp26.png'
            ],
            [
                'club_code'=>'CP28',
                'url'=>'assets/img/img_logo/CP28.jpg'
            ],
            [
                'club_code'=>'CP31',
                'url'=>'assets/img/img_logo/CP31.png'
            ],
            [
                'club_code'=>'CP37',
                'url'=>'assets/img/img_logo/CP37.jpg'
            ],
            [
                'club_code'=>'-F01',
                'url'=>'assets/img/img_logo/-F01.png'
            ],
            [
                'club_code'=>'GC00',
                'url'=>'assets/img/img_logo/GC00.jpg'
            ],
            [
                'club_code'=>'GC01',
                'url'=>'assets/img/img_logo/GC01.jpg'
            ],
            [
                'club_code'=>'GC02',
                'url'=>'assets/img/img_logo/GC02.png'
            ],
            [
                'club_code'=>'GC03',
                'url'=>'assets/img/img_logo/GC03.jpg'
            ],
            [
                'club_code'=>'GC05',
                'url'=>'assets/img/img_logo/GC05.jpg'
            ],
            [
                'club_code'=>'GC06',
                'url'=>'assets/img/img_logo/GC06.jpg'
            ],
            [
                'club_code'=>'GC07',
                'url'=>'assets/img/img_logo/GC07.png'
            ],
            [
                'club_code'=>'GC08',
                'url'=>'assets/img/img_logo/GC08.jpg'
            ],
            [
                'club_code'=>'GC10',
                'url'=>'assets/img/img_logo/GC10.jpg'
            ],
            [
                'club_code'=>'GC14',
                'url'=>'assets/img/img_logo/GC14.jpg'
            ],
            [
                'club_code'=>'GC20',
                'url'=>'assets/img/img_logo/GC20.jpg'
            ],
            [
                'club_code'=>'GC51',
                'url'=>'assets/img/img_logo/GC51.jpg'
            ],
            [
                'club_code'=>'GC54',
                'url'=>'assets/img/img_logo/GC54.jpg'
            ],
            [
                'club_code'=>'GC55',
                'url'=>'assets/img/img_logo/GC55.jpg'
            ],
            [
                'club_code'=>'GC59',
                'url'=>'assets/img/img_logo/GC59.jpg'
            ],
            [
                'club_code'=>'GC61',
                'url'=>'assets/img/img_logo/GC61.jpg'
            ],
            [
                'club_code'=>'GC66',
                'url'=>'assets/img/img_logo/GC66.jpg'
            ],
            [
                'club_code'=>'LV00',
                'url'=>'assets/img/img_logo/LV00.png'
            ],
            [
                'club_code'=>'LV01',
                'url'=>'assets/img/img_logo/LV01.png'
            ],
            [
                'club_code'=>'LV02',
                'url'=>'assets/img/img_logo/LV02.jpg'
            ],
            [
                'club_code'=>'LV03',
                'url'=>'assets/img/img_logo/LV03.png'
            ],
            [
                'club_code'=>'LV05',
                'url'=>'assets/img/img_logo/LV05.png'
            ],
            [
                'club_code'=>'LV06',
                'url'=>'assets/img/img_logo/LV06.jpg'
            ],
            [
                'club_code'=>'LV17',
                'url'=>'assets/img/img_logo/LV17.jpg'
            ],
            [
                'club_code'=>'LV25',
                'url'=>'assets/img/img_logo/LV25.jpg'
            ],
            [
                'club_code'=>'LV27',
                'url'=>'assets/img/img_logo/LV27.png'
            ],
            [
                'club_code'=>'LV35',
                'url'=>'assets/img/img_logo/LV35.png'
            ],
            [
                'club_code'=>'LV51',
                'url'=>'assets/img/img_logo/LV51.jpg'
            ],
            [
                'club_code'=>'LV52',
                'url'=>'assets/img/img_logo/LV52.jpg'
            ],
            [
                'club_code'=>'LV57',
                'url'=>'assets/img/img_logo/LV57.jpg'
            ],
            [
                'club_code'=>'LV65',
                'url'=>'assets/img/img_logo/LV65.png'
            ],
            [
                'club_code'=>'LV70',
                'url'=>'assets/img/img_logo/LV70.BMP'
            ],
            [
                'club_code'=>'LV70',
                'url'=>'assets/img/img_logo/LV70.JPG'
            ],
            [
                'club_code'=>'LV78',
                'url'=>'assets/img/img_logo/LV78.png'
            ],
            [
                'club_code'=>'LV81',
                'url'=>'assets/img/img_logo/LV81.jpg'
            ],
            [
                'club_code'=>'LV99',
                'url'=>'assets/img/img_logo/LV99.jpg'
            ],
            [
                'club_code'=>'ML00',
                'url'=>'assets/img/img_logo/ML00.png'
            ],
            [
                'club_code'=>'ML05',
                'url'=>'assets/img/img_logo/ML05.png'
            ],
            [
                'club_code'=>'MM00',
                'url'=>'assets/img/img_logo/MM00.png'
            ],
            [
                'club_code'=>'MM01',
                'url'=>'assets/img/img_logo/MM01.jpeg'
            ],
            [
                'club_code'=>'MM01',
                'url'=>'assets/img/img_logo/MM01.jpg'
            ],
            [
                'club_code'=>'MM04',
                'url'=>'assets/img/img_logo/MM04.jpg'
            ],
            [
                'club_code'=>'MM06',
                'url'=>'assets/img/img_logo/MM06.png'
            ],
            [
                'club_code'=>'MM17',
                'url'=>'assets/img/img_logo/MM17.png'
            ],
            [
                'club_code'=>'MM20',
                'url'=>'assets/img/img_logo/MM20.jpg'
            ],
            [
                'club_code'=>'MM21',
                'url'=>'assets/img/img_logo/MM21.png'
            ],
            [
                'club_code'=>'none',
                'url'=>'assets/img/img_logo/none.png'
            ],
            [
                'club_code'=>'RL00',
                'url'=>'assets/img/img_logo/RL00.jpg'
            ],
            [
                'club_code'=>'RL04',
                'url'=>'assets/img/img_logo/RL04.jpg'
            ],
            [
                'club_code'=>'RL05',
                'url'=>'assets/img/img_logo/RL05.jpg'
            ],
            [
                'club_code'=>'RL06',
                'url'=>'assets/img/img_logo/RL06.jpeg'
            ],
            [
                'club_code'=>'RL06',
                'url'=>'assets/img/img_logo/RL06.jpg'
            ],
            [
                'club_code'=>'VB00',
                'url'=>'assets/img/img_logo/VB00.jpg'
            ],
            [
                'club_code'=>'VB02',
                'url'=>'assets/img/img_logo/VB02.jpg'
            ],
            [
                'club_code'=>'vb03',
                'url'=>'assets/img/img_logo/vb03.jpg'
            ],
            [
                'club_code'=>'VB03',
                'url'=>'assets/img/img_logo/VB03.png'
            ],
            [
                'club_code'=>'vb04',
                'url'=>'assets/img/img_logo/vb04.png'
            ],
            [
                'club_code'=>'VB05',
                'url'=>'assets/img/img_logo/VB05.jpg'
            ],
            [
                'club_code'=>'VB08',
                'url'=>'assets/img/img_logo/VB08.jpg'
            ],
            [
                'club_code'=>'vb09',
                'url'=>'assets/img/img_logo/vb09.jpg'
            ],
            [
                'club_code'=>'vb10',
                'url'=>'assets/img/img_logo/vb10.jpg'
            ],
            [
                'club_code'=>'vb13',
                'url'=>'assets/img/img_logo/vb13.jpg'
            ],
            [
                'club_code'=>'vb14',
                'url'=>'assets/img/img_logo/vb14.png'
            ],
            [
                'club_code'=>'vb16',
                'url'=>'assets/img/img_logo/vb16.jpg'
            ],
            [
                'club_code'=>'vb23',
                'url'=>'assets/img/img_logo/vb23.jpg'
            ],
        ];

        foreach ($data as $dat)
        {
            ImgLogo::create($dat);
        }
    }
}
